### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by nicostrebel** [PurpleHorrorRus/simple-helix-api#2]
I've followed the instructions but get the following error:

> const { id } = await Helix.getUser(botname);
>                ^^^^^
> 
> SyntaxError: await is only valid in async function

**Comment by PurpleHorrorRus** [comment]
Your function must be asynchronous.
You can read more about it [here](https://javascript.info/async-await)
Or you can use .then(...) instead, but I recommend you learn asynchronous functions

**Comment by PurpleHorrorRus** [comment]
If you have no more questions, I close this issue
